### ISSUE TITLE
Matrix4Base has a "compiler is unable to type-check this expression in a reasonable time" error in identity declaration

### ISSUE THREAD

**Issue by Kiwijane3** [CooperCorona/CoronaMath#22]
Hi, I'm trying to use you Voronoi cell library, and I'm running into a compiler error in Matrix4Base, at the identity part.

**Comment by CooperCorona** [comment]
Hi Kiwijane3,

Sorry for the delay. I've run into this issue before but I thought I fixed it on the CoronaMath end. If I had to guess, I need to tag a new version of [Voronoi](https://github.com/CooperCorona/Voronoi) so it pulls those changes. I'll look into it. Feel free to comment a reminder if I don't get to it soon. Thanks for the heads up!

**Comment by Kiwijane3** [comment]
Thanks. I just thought I’d add that this is only happening with ARM-based builds; x64 builds fine, at least on my hardware.

**Comment by CooperCorona** [comment]
Hi Kiwijane3,

I've pushed release 1.3.4. This _should_ break up the line that causes the "compiler is unable to type-check this expression in a reasonable time" error. Please run `swift package update` from whatever project is using [Voronoi](https://github.com/CooperCorona/Voronoi) (or Voronoi itself). You should see version 1.3.4 of CoronaMath (which should appear in your Package.resolved file). Then, try building it.

If this doesn't work, can you comment with more error logs or screenshots?

**Comment by Kiwijane3** [comment]
That works perfectly. Thank you so much. I'll close the issue now
